from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel
from typing import Optional, List

app = FastAPI(
    title="AI Generated API",
    description="Auto-generated by n8n AI Code Generator",
    version="1.0.0"
)

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# Routes

@app.get("/entity1")
def get_entity1():
    """"""
    return {"message": "ok", "endpoint": "/entity1"}

@app.post("/entity1")
def post_entity1():
    """Create Entity1"""
    return {"message": "ok", "endpoint": "/entity1"}

@app.put("/entity1/{id}")
def put_entity1_id():
    """Update Entity1"""
    return {"message": "ok", "endpoint": "/entity1/{id}"}

@app.delete("/entity1/{id}")
def delete_entity1_id():
    """Delete Entity1 by id"""
    return {"message": "ok", "endpoint": "/entity1/{id}"}

@app.get("/entity2")
def get_entity2():
    """"""
    return {"message": "ok", "endpoint": "/entity2"}

@app.post("/entity2")
def post_entity2():
    """Create Entity2"""
    return {"message": "ok", "endpoint": "/entity2"}

@app.put("/entity2/{id}")
def put_entity2_id():
    """Update Entity2"""
    return {"message": "ok", "endpoint": "/entity2/{id}"}

@app.delete("/entity2/{id}")
def delete_entity2_id():
    """Delete Entity2 by id"""
    return {"message": "ok", "endpoint": "/entity2/{id}"}
